#!/bin/bash
echo this script done by rk
echo Installing software-properties-common packages, then add the java OpenJDK PPA repository.
sudo apt install software-properties-common apt-transport-https -y
sudo add-apt-repository ppa:openjdk-r/ppa -y
Now installing the Java 8 using apt command.
sudo apt install openjdk-8-jdk -y
echo java version installed on the system.
java -version
echo updating and upgrading the version
sudo apt-get update -y
sudo apt-get upgrade -y
echo Ansible PPA to your server
sudo apt-add-repository ppa:ansible/ansible
echo update the repository and install Ansible
sudo apt-get update -y
sudo apt-get install ansible -y
echo Ansible version
sudo ansible --version
echo keygen
ssh-keygen
echo ansbile hosts
sudo vi /etc/ansible/hosts
